import { EventEmitter } from '../../stencil-public-runtime';
import { Environment } from '../../config';
import { IMFAResponse } from '../../interfaces/common';
export declare class MfaModelPopUP {
    operationsToken: string;
    userScopedAccessToken: string;
    environment: Environment;
    onClose: () => void;
    mfaResponse: IMFAResponse | null;
    addRequestPayload: any;
    initialMfaResponse: any;
    requestType: 'card' | 'bank';
    time: number;
    isRunning: boolean;
    currentInquiryId: string;
    timer: any;
    private countdownIntervalId;
    private pollingIntervalId;
    errorHandler?: (messages: string[]) => void;
    accountSubmissionSuccess: any;
    noOfAttempts: number;
    private timeoutId;
    successEvent: EventEmitter<any>;
    handleIsRunningTrue(newValue: boolean): void;
    handleIsRunningFalse(newValue: boolean): void;
    private handleStart;
    private handleStop;
    componentWillLoad(): void;
    componentDidLoad(): void;
    scheduleMfaStatusPolling(): void;
    handleMfaResponseChanged(newValue: IMFAResponse | null): Promise<void>;
    handleAccountSubmissionSuccessChanged(newValue: any): void;
    clearPollingTimers(): void;
    startCountdownTimer(): void;
    stopCountdownTimer(): void;
    disconnectedCallback(): void;
    handleResendLinkClick: () => Promise<void>;
    handleCancel: () => void;
    get mfaPoolSettings(): string;
    get mobileNumberLastFourDigits(): string;
    get startInterval(): number;
    get recurringInterval(): number;
    private formatTime;
    private getAttemptLabel;
    render(): any;
}
