import { EventEmitter } from '../../stencil-public-runtime';
import { Environment } from '../../config';
import { BankAccountType } from "../../interfaces/common";
export declare class AddBankAccount {
    goToPaymentSelector: EventEmitter<boolean>;
    addressValidation: EventEmitter<string>;
    private errorBannerRef;
    private devLog;
    formattedMobileNumber: string;
    operationsToken: string;
    userScopedAccessToken: string;
    environment: Environment;
    bankAccountAdded: EventEmitter<string>;
    accountHolderName: string;
    accountNumber: string;
    routingNumber: string;
    bankAccountType: BankAccountType;
    dateofBirth: string;
    paymentAccountNickname: string;
    firstName: string;
    lastName: string;
    address1: string;
    address2: string;
    city: string;
    state: string;
    country: string;
    zipCode: string;
    mobilePhoneNumber: string;
    selectedPhoneCode: string;
    isPhoneCodeDropdownOpen: boolean;
    emailAddress: string;
    apiErrors: {
        [key: string]: string[];
    };
    isLoading: boolean;
    mfaPopUp: boolean;
    PaymentAccountRequestPayload: any;
    mfaResponsePayload: any;
    brokenRules: string[];
    isAddressSuggestion: boolean;
    isVerifying: boolean;
    errors: {
        accountHolderName: string;
        accountNumber: string;
        routingNumber: string;
        bankAccountType: string;
        firstName: string;
        lastName: string;
        address1: string;
        address2: string;
        dateofBirth: string;
        paymentAccountNickname: string;
        city: string;
        state: string;
        country: string;
        zipCode: string;
        mobilePhoneNumber: string;
        emailAddress: string;
        selectedPhoneCode: string;
    };
    isAddressResubmission: boolean;
    el: HTMLElement;
    private dropdownWrapper;
    componentWillLoad(): void;
    handleInputChange(field: string, value: string): void;
    handleMobileNumberChange(event: Event): void;
    private showErrorBanner;
    private scrollToView;
    handleStateChange(event: Event): void;
    isCountryUS(): boolean;
    isCountryUSorCanada(): boolean;
    getProvinceOrStateCode(): string;
    getDefaultState(): string;
    handleCountryChange(event: Event): void;
    handlePhoneCodeChange(event: Event): void;
    handleBirthDateChange(value: string): void;
    validateMobilePhoneNumber(): {
        [key: string]: string;
    };
    validateEmailAddress(): {
        [key: string]: string;
    };
    validateSelectedPhoneCode(): {
        [key: string]: string;
    };
    togglePhoneCodeDropdown: (event: MouseEvent) => void;
    selectPhoneCode: (code: string) => void;
    handleOutsideClick: (event: MouseEvent) => void;
    handleEscapePress: (event: KeyboardEvent) => void;
    private removeDropdownListeners;
    handleClosePopup: () => void;
    private handleMfaError;
    private validateAccountFields;
    private validatePersonalFields;
    private validateDateOfBirth;
    private validateAddressFields;
    validate(): boolean;
    private scrollToFirstError;
    handleSubmit(event: Event): Promise<void>;
    private formatDateForAPI;
    private handleSuccess;
    private handleResponseError;
    private applySuggested;
    private handleUnknownError;
    private handleAddressValidation;
    private handleValidationError;
    resetForm(): void;
    goToWallet: () => void;
    private handleCloseBanner;
    private renderErrorBanner;
    private renderAccountFields;
    private renderPersonalInfo;
    private renderAddressSection;
    private renderApiErrors;
    private renderFormActions;
    render(): any;
}
