/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "./stencil-public-runtime";
import { Environment } from "./config";
import { CreditCardType } from "./utils/apiService";
import { PaymentOption } from "./components/walletdropdown/walletdropdown";
export { Environment } from "./config";
export { CreditCardType } from "./utils/apiService";
export { PaymentOption } from "./components/walletdropdown/walletdropdown";
export namespace Components {
    interface AddBankAccount {
        "environment": Environment;
        "operationsToken": string;
        "userScopedAccessToken": string;
    }
    interface AddNewPayment {
        "availableCreditCards"?: CreditCardType[] | null;
        "environment": Environment;
        "operationsToken": string;
        "userScopedAccessToken": string;
    }
    interface DatePicker {
        "inputId": string;
        "minAge"?: number;
        "placeholder": string;
        "value": string;
    }
    interface MfaModelPopup {
        "addRequestPayload": any;
        "environment": Environment;
        "errorHandler"?: (messages: string[]) => void;
        "initialMfaResponse": any;
        "onClose": () => void;
        "operationsToken": string;
        "requestType": 'card' | 'bank';
        "userScopedAccessToken": string;
    }
    interface PaymentDate {
    }
    interface WalletDropdown {
        "displayMode": 'full' | 'text-only';
        "environment": Environment;
        "operationsToken": string;
        "options": string | string[];
        "paymentType": string;
        "selectPayment": string;
        "userScopedAccessToken": string;
    }
}
export interface AddBankAccountCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAddBankAccountElement;
}
export interface AddNewPaymentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAddNewPaymentElement;
}
export interface DatePickerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDatePickerElement;
}
export interface MfaModelPopupCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMfaModelPopupElement;
}
export interface PaymentDateCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPaymentDateElement;
}
export interface WalletDropdownCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWalletDropdownElement;
}
declare global {
    interface HTMLAddBankAccountElementEventMap {
        "goToPaymentSelector": boolean;
        "addressValidation": string;
        "bankAccountAdded": string;
    }
    interface HTMLAddBankAccountElement extends Components.AddBankAccount, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAddBankAccountElementEventMap>(type: K, listener: (this: HTMLAddBankAccountElement, ev: AddBankAccountCustomEvent<HTMLAddBankAccountElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAddBankAccountElementEventMap>(type: K, listener: (this: HTMLAddBankAccountElement, ev: AddBankAccountCustomEvent<HTMLAddBankAccountElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAddBankAccountElement: {
        prototype: HTMLAddBankAccountElement;
        new (): HTMLAddBankAccountElement;
    };
    interface HTMLAddNewPaymentElementEventMap {
        "goToPaymentSelector": boolean;
        "addressValidation": string;
        "cardAdded": string;
    }
    interface HTMLAddNewPaymentElement extends Components.AddNewPayment, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAddNewPaymentElementEventMap>(type: K, listener: (this: HTMLAddNewPaymentElement, ev: AddNewPaymentCustomEvent<HTMLAddNewPaymentElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAddNewPaymentElementEventMap>(type: K, listener: (this: HTMLAddNewPaymentElement, ev: AddNewPaymentCustomEvent<HTMLAddNewPaymentElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAddNewPaymentElement: {
        prototype: HTMLAddNewPaymentElement;
        new (): HTMLAddNewPaymentElement;
    };
    interface HTMLDatePickerElementEventMap {
        "dateChange": string;
    }
    interface HTMLDatePickerElement extends Components.DatePicker, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDatePickerElementEventMap>(type: K, listener: (this: HTMLDatePickerElement, ev: DatePickerCustomEvent<HTMLDatePickerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDatePickerElementEventMap>(type: K, listener: (this: HTMLDatePickerElement, ev: DatePickerCustomEvent<HTMLDatePickerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDatePickerElement: {
        prototype: HTMLDatePickerElement;
        new (): HTMLDatePickerElement;
    };
    interface HTMLMfaModelPopupElementEventMap {
        "successEvent": any;
    }
    interface HTMLMfaModelPopupElement extends Components.MfaModelPopup, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMfaModelPopupElementEventMap>(type: K, listener: (this: HTMLMfaModelPopupElement, ev: MfaModelPopupCustomEvent<HTMLMfaModelPopupElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMfaModelPopupElementEventMap>(type: K, listener: (this: HTMLMfaModelPopupElement, ev: MfaModelPopupCustomEvent<HTMLMfaModelPopupElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMfaModelPopupElement: {
        prototype: HTMLMfaModelPopupElement;
        new (): HTMLMfaModelPopupElement;
    };
    interface HTMLPaymentDateElementEventMap {
        "updateDate": string;
    }
    interface HTMLPaymentDateElement extends Components.PaymentDate, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPaymentDateElementEventMap>(type: K, listener: (this: HTMLPaymentDateElement, ev: PaymentDateCustomEvent<HTMLPaymentDateElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPaymentDateElementEventMap>(type: K, listener: (this: HTMLPaymentDateElement, ev: PaymentDateCustomEvent<HTMLPaymentDateElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPaymentDateElement: {
        prototype: HTMLPaymentDateElement;
        new (): HTMLPaymentDateElement;
    };
    interface HTMLWalletDropdownElementEventMap {
        "selectOption": PaymentOption;
    }
    interface HTMLWalletDropdownElement extends Components.WalletDropdown, HTMLStencilElement {
        addEventListener<K extends keyof HTMLWalletDropdownElementEventMap>(type: K, listener: (this: HTMLWalletDropdownElement, ev: WalletDropdownCustomEvent<HTMLWalletDropdownElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLWalletDropdownElementEventMap>(type: K, listener: (this: HTMLWalletDropdownElement, ev: WalletDropdownCustomEvent<HTMLWalletDropdownElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLWalletDropdownElement: {
        prototype: HTMLWalletDropdownElement;
        new (): HTMLWalletDropdownElement;
    };
    interface HTMLElementTagNameMap {
        "add-bank-account": HTMLAddBankAccountElement;
        "add-new-payment": HTMLAddNewPaymentElement;
        "date-picker": HTMLDatePickerElement;
        "mfa-model-popup": HTMLMfaModelPopupElement;
        "payment-date": HTMLPaymentDateElement;
        "wallet-dropdown": HTMLWalletDropdownElement;
    }
}
declare namespace LocalJSX {
    interface AddBankAccount {
        "environment"?: Environment;
        "onAddressValidation"?: (event: AddBankAccountCustomEvent<string>) => void;
        "onBankAccountAdded"?: (event: AddBankAccountCustomEvent<string>) => void;
        "onGoToPaymentSelector"?: (event: AddBankAccountCustomEvent<boolean>) => void;
        "operationsToken"?: string;
        "userScopedAccessToken"?: string;
    }
    interface AddNewPayment {
        "availableCreditCards"?: CreditCardType[] | null;
        "environment"?: Environment;
        "onAddressValidation"?: (event: AddNewPaymentCustomEvent<string>) => void;
        "onCardAdded"?: (event: AddNewPaymentCustomEvent<string>) => void;
        "onGoToPaymentSelector"?: (event: AddNewPaymentCustomEvent<boolean>) => void;
        "operationsToken"?: string;
        "userScopedAccessToken"?: string;
    }
    interface DatePicker {
        "inputId"?: string;
        "minAge"?: number;
        "onDateChange"?: (event: DatePickerCustomEvent<string>) => void;
        "placeholder"?: string;
        "value"?: string;
    }
    interface MfaModelPopup {
        "addRequestPayload"?: any;
        "environment"?: Environment;
        "errorHandler"?: (messages: string[]) => void;
        "initialMfaResponse"?: any;
        "onClose"?: () => void;
        "onSuccessEvent"?: (event: MfaModelPopupCustomEvent<any>) => void;
        "operationsToken"?: string;
        "requestType"?: 'card' | 'bank';
        "userScopedAccessToken"?: string;
    }
    interface PaymentDate {
        "onUpdateDate"?: (event: PaymentDateCustomEvent<string>) => void;
    }
    interface WalletDropdown {
        "displayMode"?: 'full' | 'text-only';
        "environment"?: Environment;
        "onSelectOption"?: (event: WalletDropdownCustomEvent<PaymentOption>) => void;
        "operationsToken"?: string;
        "options"?: string | string[];
        "paymentType"?: string;
        "selectPayment"?: string;
        "userScopedAccessToken"?: string;
    }
    interface IntrinsicElements {
        "add-bank-account": AddBankAccount;
        "add-new-payment": AddNewPayment;
        "date-picker": DatePicker;
        "mfa-model-popup": MfaModelPopup;
        "payment-date": PaymentDate;
        "wallet-dropdown": WalletDropdown;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "add-bank-account": LocalJSX.AddBankAccount & JSXBase.HTMLAttributes<HTMLAddBankAccountElement>;
            "add-new-payment": LocalJSX.AddNewPayment & JSXBase.HTMLAttributes<HTMLAddNewPaymentElement>;
            "date-picker": LocalJSX.DatePicker & JSXBase.HTMLAttributes<HTMLDatePickerElement>;
            "mfa-model-popup": LocalJSX.MfaModelPopup & JSXBase.HTMLAttributes<HTMLMfaModelPopupElement>;
            "payment-date": LocalJSX.PaymentDate & JSXBase.HTMLAttributes<HTMLPaymentDateElement>;
            "wallet-dropdown": LocalJSX.WalletDropdown & JSXBase.HTMLAttributes<HTMLWalletDropdownElement>;
        }
    }
}
